"""Add reminder fields attempt 4

Revision ID: 3f49afb18411
Revises: e8f673995456
Create Date: 2026-02-03 07:10:10.374625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f49afb18411'
down_revision = 'e8f673995456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_custom_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('reminder_custom_message')
        batch_op.drop_column('reminder_enabled')

    # ### end Alembic commands ###
