"""Add TeamMember and Task assignment

Revision ID: e8f673995456
Revises: 118d1111787f
Create Date: 2026-02-03 00:08:32.954123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f673995456'
down_revision = '118d1111787f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('team_member',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('role', sa.String(length=50), nullable=True),
    # sa.Column('email', sa.String(length=120), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email')
    # )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_team_member', 'team_member', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_team_member', type_='foreignkey')
        batch_op.drop_column('assigned_to_id')

    op.drop_table('team_member')
    # ### end Alembic commands ###
